import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    brand: "Pink Flyod",
    name: "The Wall Art Hoodie",
    price: 799,
    originalPrice: 1499,
    averageRating: 4.5,
    category: "Hoodies",
    onSale: true,
    inStock: true,
    img: "https://bit.ly/3o3Pa18",
  },
  {
    _id: uuid(),
    brand: "Fully Filmy",
    name: "Don't Mess With John Wick Phone Case",
    price: 599,
    originalPrice: 999,
    averageRating: 3.8,
    category: "Accessories",
    onSale: false,
    inStock: true,
    img: "https://bit.ly/436VALw",
  },
  {
    _id: uuid(),
    brand: "Fully Filmy",
    name: "Pulp Fiction Tribute Poster",
    price: 189,
    originalPrice: 299,
    averageRating: 4.2,
    category: "Posters",
    onSale: false,
    inStock: false,
    img: "https://bit.ly/3pKDJvT",
  },
  {
    _id: uuid(),
    brand: "AC/DC",
    name: "Highway - Accessory Pouch [8.5 X 6]",
    price: 599,
    originalPrice: 899,
    averageRating: 2.5,
    category: "Accessories",
    onSale: true,
    inStock: true,
    img: "https://t.ly/F_fAm",
  },
  {
    _id: uuid(),
    brand: "Logic",
    name: "Bobby Tarantino Logo Hoodie",
    price: 999,
    originalPrice: 2399,
    averageRating: 4.6,
    category: "Hoodies",
    onSale: false,
    inStock: false,
    img: "https://t.ly/hadz",
  },
  {
    _id: uuid(),
    brand: "Imagine Dragons",
    name: "Patch | Transcend Logo Patch",
    price: 299,
    originalPrice: 1299,
    averageRating: 4.8,
    category: "Accessories",
    onSale: true,
    inStock: true,
    img: "https://t.ly/CNZX",
  },
  {
    _id: uuid(),
    brand: "Fully Filmy",
    name: "Kamal Tribute",
    price: 169,
    originalPrice: 399,
    averageRating: 2.3,
    category: "Posters",
    onSale: false,
    inStock: true,
    img: "https://t.ly/8kJm",
  },
  {
    _id: uuid(),
    brand: "Harry Styles",
    name: "Treat People With Kindness Hoodie Black",
    price: 899,
    originalPrice: 1699,
    averageRating: 3.5,
    category: "Hoodies",
    onSale: false,
    inStock: true,
    img: "https://t.ly/H-QX",
  },
  {
    _id: uuid(),
    brand: "David Bowie",
    name: "White, Blue & Red 75th Logo Hoodie",
    price: 649,
    originalPrice: 999,
    averageRating: 1.8,
    category: "Hoodies",
    onSale: false,
    inStock: true,
    img: "https://t.ly/PrqF",
  },
  {
    _id: uuid(),
    brand: "Fully Filmy",
    name: "Leo the Wolf Poster",
    price: 349,
    originalPrice: 799,
    averageRating: 4.3,
    category: "Posters",
    onSale: true,
    inStock: true,
    img: "https://t.ly/QoCh",
  },
  {
    _id: uuid(),
    brand: "Fully Filmy",
    name: "Titan Inside Cover",
    price: 599,
    originalPrice: 999,
    averageRating: 3.3,
    category: "Accessories",
    onSale: false,
    inStock: false,
    img: "https://t.ly/sA_4",
  },
  {
    _id: uuid(),
    brand: "Billy Joel",
    name: "NY MSG Event Poster",
    price: 899,
    originalPrice: 1699,
    averageRating: 4.0,
    category: "Posters",
    onSale: false,
    inStock: false,
    img: "https://t.ly/UswC",
  },
];
