export const ACTION_TYPE = {
  INIT_CATEGORIES: "INIT_CATEGORIES",
  INIT_PRODUCTS: "INIT_PRODUCTS",
  SORT_BY: "SORT_BY",
  TOGGLE_CATEGORY: "TOGGLE_CATEGORY",
  TOGGLE_STOCK: "TOGGLE_STOCK",
  PRICE_RANGE: "PRICE_RANGE",
  SEARH: "SEARCH",
  CLEAR_ALL: "CLEAR_ALL",
  SHOW_TOAST: "SHOW_TOAST",
};
