export const ACTION_TYPE = {
  INIT_CATEGORIES: "INIT_CATEGORIES",
  INIT_PRODUCTS: "INIT_PRODUCTS",
  SORT_BY: "SORT_BY",
  TOGGLE_CATEGORY: "TOGGLE_CATEGORY",
  TOGGLE_STOCK: "TOGGLE_STOCK",
  RATING_RANGE: "RATING_RANGE",
  SEARCH: "SEARCH",
  CLEAR_FILTER: "CLEAR_FILTER",
  SHOW_TOAST: "SHOW_TOAST",
  SHOW_ERROR: "SHOW_ERROR",
  SHOW_LOADER: "SHOW_LOADER",
};
